#lang racket/base
(require rackunit)
(require "./add.rkt")
(require "./mul.rkt")
(require "./mixed.rkt")
(require "./decl.rkt")
(require "./fun.rkt")
(require "./if.rkt")
(require "./assign.rkt")

(provide (all-defined-out))

(define (test-L5 interpret)
  (check-equal? (interpret add-0-in) add-0-out)
  (check-equal? (interpret add-1-in) add-1-out)
  (check-equal? (interpret add-2-in) add-2-out)
  (check-equal? (interpret add-3-in) add-3-out)

  (check-equal? (interpret mul-0-in) mul-0-out)
  (check-equal? (interpret mul-1-in) mul-1-out)
  (check-equal? (interpret mul-2-in) mul-2-out)
  (check-equal? (interpret mul-3-in) mul-3-out)
  
  (check-equal? (interpret mix-0-in) mix-0-out)
  (check-equal? (interpret mix-1-in) mix-1-out)
  (check-equal? (interpret mix-2-in) mix-2-out)
  (check-equal? (interpret mix-3-in) mix-3-out)

  (check-equal? (interpret decl-1-in) decl-out)
  (check-equal? (interpret decl-2-in) decl-out)
  (check-equal? (interpret decl-3-in) decl-out)
  (check-equal? (interpret decl-4-in) decl-out)
  (check-equal? (interpret decl-5-in) decl-out)
  (check-equal? (interpret decl-6-in) decl-out)
  (check-equal? (interpret decl-7-in) decl-out)
  (check-equal? (interpret decl-8-in) decl-out)
  (check-equal? (interpret decl-9-in) decl-out)
  
  (check-equal? (interpret function-1-in) function-1-out)
  (check-equal? (interpret function-2-in) function-2-out)
  (check-equal? (interpret function-3-in) function-3-out)
  (check-equal? (interpret function-4-in) function-4-out)
  (check-equal? (interpret function-5-in) function-5-out)
  (check-equal? (interpret function-6-in) function-6-out)
  (check-equal? (interpret function-7-in) function-7-out)
  (check-equal? (interpret function-8-in) function-8-out)
  (check-equal? (interpret function-9-in) function-9-out)
  (check-equal? (interpret function-10-in) function-10-out)
  (check-equal? (interpret function-11-in) function-11-out)
  (check-equal? (interpret function-12-in) function-12-out)
  (check-equal? (interpret function-13-in) function-13-out)
  (check-equal? (interpret function-14-in) function-14-out)
  (check-equal? (interpret function-15-in) function-15-out)
  
  (check-equal? (interpret if-0-in) if-0-out)
  (check-equal? (interpret if-1-in) if-1-out)
  (check-equal? (interpret if-2-in) if-2-out)
  (check-equal? (interpret if-3-in) if-3-out)
  (check-equal? (interpret if-4-in) if-4-out)
  (check-equal? (interpret if-5-in) if-5-out)
  (check-equal? (interpret if-6-in) if-6-out)
  (check-equal? (interpret if-7-in) if-7-out)
  (check-equal? (interpret if-8-in) if-8-out)
  (check-equal? (interpret if-9-in) if-9-out)
  (check-equal? (interpret if-10-in) if-10-out)
  (check-equal? (interpret if-11-in) if-11-out)
  (check-equal? (interpret if-12-in) if-12-out)
  (check-equal? (interpret if-13-in) if-13-out)
  (check-equal? (interpret if-14-in) if-14-out)
  (check-equal? (interpret if-15-in) if-15-out)
  (check-equal? (interpret if-16-in) if-16-out)
  
  (check-equal? (interpret assign-1-in) assign-1-out)
  (check-equal? (interpret assign-2-in) assign-2-out)
  (check-equal? (interpret assign-3-in) assign-3-out)
  (check-equal? (interpret assign-4-in) assign-4-out)
  (check-equal? (interpret assign-5-in) assign-5-out)
  (check-equal? (interpret assign-6-in) assign-6-out)
  (check-equal? (interpret assign-7-in) assign-7-out)
  (check-equal? (interpret assign-8-in) assign-8-out)
  (check-equal? (interpret assign-9-in) assign-9-out)
  (check-equal? (interpret assign-10-in) assign-10-out)
  (check-equal? (interpret assign-11-in) assign-11-out)
  (check-equal? (interpret assign-12-in) assign-12-out)
  (check-equal? (interpret assign-13-in) assign-13-out)
  (check-equal? (interpret assign-14-in) assign-14-out)
  (check-equal? (interpret assign-15-in) assign-15-out)
  (check-equal? (interpret assign-16-in) assign-16-out))

